### ISSUE TITLE
horizontal-scaling-with-kubectl-scale - deployment issue

### ISSUE THREAD

**Issue by bryfry** [alta3/kubernetes-the-alta3-way#29]
When testing #27 the below error occurred when [horizontal-scaling-with-kubectl-scale/test.sh](https://github.com/alta3/kubernetes-the-alta3-way/blob/f40038e2ea1732fa02b877c16b78a25515421ad2/labs/setup/horizontal-scaling-with-kubectl-scale/test.sh)

Confirmed this is not a 1.24 issue by getting the same error on the current main branch

```
[+] Testing horizontal-scaling-with-kubectl-scale
deployment.apps/sise-deploy created
deployment.apps/sise-deploy condition met
deployment.apps/sise-deploy scaled
error: error validating "../yaml/webby-deploy.yaml": error validating data: kind not set; if you choose to ignore these errors, turn validation off with --validate=false
error: the path "deployments/webby-deploy" does not exist
Error from server (NotFound): deployments.apps "webservice" not found
```

**Comment by BicycleWalrus** [comment]
This is failing because the manuscript you are attempting to run is a blank template. When the student fills it out, it will perform the exact same function as sise-deploy.yaml --

I recommend deleting the webby-deploy.yaml portion of your test script, as there is no effective difference between the two manifests.

**Comment by BicycleWalrus** [comment]
Or -- You could test against the webby-deploy-filled-out.yaml manifest

**Comment by BicycleWalrus** [comment]
Closing this issue, as there is no bug. Recommend one of two options

1. Delete the webby-deploy portion of the test script because it tests no additional functionality over sise-deploy.
2. Test against the webby-deploy-filled-out.yaml manifest, which would test against a properly completed manifest the students should produce when completing this lab step.

**Comment by bryfry** [comment]
Using option #2:
> Test against the webby-deploy-filled-out.yaml manifest, which would test against a properly completed manifest the students should produce when completing this lab step.

Implemented and tested: https://github.com/alta3/kubernetes-the-alta3-way/commit/117a42b6d27a1fc52cd268d9422d9b4ff9caa936

Thanks @BicycleWalrus!
